//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationClient.AVServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoReqBase", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplicationClient.AVServiceReference.ProductDTOReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplicationClient.AVServiceReference.UserDTOReq))]
    public partial class CatalogoReqBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.Paginacion PaginacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.Accion TipoOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Control {
            get {
                return this.ControlField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlField, value) != true)) {
                    this.ControlField = value;
                    this.RaisePropertyChanged("Control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((this.OperacionField.Equals(value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.Paginacion Paginacion {
            get {
                return this.PaginacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginacionField, value) != true)) {
                    this.PaginacionField = value;
                    this.RaisePropertyChanged("Paginacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seguridad {
            get {
                return this.SeguridadField;
            }
            set {
                if ((object.ReferenceEquals(this.SeguridadField, value) != true)) {
                    this.SeguridadField = value;
                    this.RaisePropertyChanged("Seguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.Accion TipoOperacion {
            get {
                return this.TipoOperacionField;
            }
            set {
                if ((this.TipoOperacionField.Equals(value) != true)) {
                    this.TipoOperacionField = value;
                    this.RaisePropertyChanged("TipoOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrosPorPaginaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadRegistros {
            get {
                return this.CantidadRegistrosField;
            }
            set {
                if ((this.CantidadRegistrosField.Equals(value) != true)) {
                    this.CantidadRegistrosField = value;
                    this.RaisePropertyChanged("CantidadRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagina {
            get {
                return this.PaginaField;
            }
            set {
                if ((this.PaginaField.Equals(value) != true)) {
                    this.PaginaField = value;
                    this.RaisePropertyChanged("Pagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrosPorPagina {
            get {
                return this.RegistrosPorPaginaField;
            }
            set {
                if ((this.RegistrosPorPaginaField.Equals(value) != true)) {
                    this.RegistrosPorPaginaField = value;
                    this.RaisePropertyChanged("RegistrosPorPagina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTOReq", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProductDTOReq : WebApplicationClient.AVServiceReference.CatalogoReqBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.ListaProduct productsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.ListaProduct products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTOReq", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class UserDTOReq : WebApplicationClient.AVServiceReference.CatalogoReqBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.ListaUsers UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.ListaUsers Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accion", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    public enum Accion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Crear = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Actualizar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelar = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eliminar = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activar = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desactivar = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consultar = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Autorizar = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrearMasivo = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anular = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generar = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmar = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transferir = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaUsers", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="UserDTO")]
    [System.SerializableAttribute()]
    public class ListaUsers : System.Collections.Generic.List<WebApplicationClient.AVServiceReference.UserDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaProduct", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="ProductDTO")]
    [System.SerializableAttribute()]
    public class ListaProduct : System.Collections.Generic.List<WebApplicationClient.AVServiceReference.ProductDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class UserDTO : WebApplicationClient.AVServiceReference.CatalogoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserCreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id")]
        public int Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((this.Id1Field.Equals(value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserCreationDate {
            get {
                return this.UserCreationDateField;
            }
            set {
                if ((this.UserCreationDateField.Equals(value) != true)) {
                    this.UserCreationDateField = value;
                    this.RaisePropertyChanged("UserCreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPasswordHash {
            get {
                return this.UserPasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordHashField, value) != true)) {
                    this.UserPasswordHashField = value;
                    this.RaisePropertyChanged("UserPasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserStatus {
            get {
                return this.UserStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.UserStatusField, value) != true)) {
                    this.UserStatusField = value;
                    this.RaisePropertyChanged("UserStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoBase", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplicationClient.AVServiceReference.UserDTO))]
    public partial class CatalogoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Usuario {
            get {
                return this.Id_UsuarioField;
            }
            set {
                if ((this.Id_UsuarioField.Equals(value) != true)) {
                    this.Id_UsuarioField = value;
                    this.RaisePropertyChanged("Id_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoRespBase", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplicationClient.AVServiceReference.ProductDTOResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplicationClient.AVServiceReference.UserDTOResp))]
    public partial class CatalogoRespBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.ListaErrores ErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.ListaErrores Errores {
            get {
                return this.ErroresField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroresField, value) != true)) {
                    this.ErroresField = value;
                    this.RaisePropertyChanged("Errores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitosa {
            get {
                return this.EsExitosaField;
            }
            set {
                if ((this.EsExitosaField.Equals(value) != true)) {
                    this.EsExitosaField = value;
                    this.RaisePropertyChanged("EsExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTOResp", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class ProductDTOResp : WebApplicationClient.AVServiceReference.CatalogoRespBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.ListaProduct productsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.ListaProduct products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTOResp", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class UserDTOResp : WebApplicationClient.AVServiceReference.CatalogoRespBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationClient.AVServiceReference.ListaUsers UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationClient.AVServiceReference.ListaUsers Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaErrores", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="Error")]
    [System.SerializableAttribute()]
    public class ListaErrores : System.Collections.Generic.List<WebApplicationClient.AVServiceReference.Error> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExcepcionInternaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception ExcepcionInterna {
            get {
                return this.ExcepcionInternaField;
            }
            set {
                if ((object.ReferenceEquals(this.ExcepcionInternaField, value) != true)) {
                    this.ExcepcionInternaField = value;
                    this.RaisePropertyChanged("ExcepcionInterna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fila {
            get {
                return this.FilaField;
            }
            set {
                if ((this.FilaField.Equals(value) != true)) {
                    this.FilaField = value;
                    this.RaisePropertyChanged("Fila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AVServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserConsultar", ReplyAction="http://tempuri.org/IService1/UserConsultarResponse")]
        WebApplicationClient.AVServiceReference.UserDTOResp UserConsultar(WebApplicationClient.AVServiceReference.UserDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserConsultar", ReplyAction="http://tempuri.org/IService1/UserConsultarResponse")]
        System.Threading.Tasks.Task<WebApplicationClient.AVServiceReference.UserDTOResp> UserConsultarAsync(WebApplicationClient.AVServiceReference.UserDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductConsultar", ReplyAction="http://tempuri.org/IService1/ProductConsultarResponse")]
        WebApplicationClient.AVServiceReference.ProductDTOResp ProductConsultar(WebApplicationClient.AVServiceReference.ProductDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductConsultar", ReplyAction="http://tempuri.org/IService1/ProductConsultarResponse")]
        System.Threading.Tasks.Task<WebApplicationClient.AVServiceReference.ProductDTOResp> ProductConsultarAsync(WebApplicationClient.AVServiceReference.ProductDTOReq req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplicationClient.AVServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplicationClient.AVServiceReference.IService1>, WebApplicationClient.AVServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationClient.AVServiceReference.UserDTOResp UserConsultar(WebApplicationClient.AVServiceReference.UserDTOReq req) {
            return base.Channel.UserConsultar(req);
        }
        
        public System.Threading.Tasks.Task<WebApplicationClient.AVServiceReference.UserDTOResp> UserConsultarAsync(WebApplicationClient.AVServiceReference.UserDTOReq req) {
            return base.Channel.UserConsultarAsync(req);
        }
        
        public WebApplicationClient.AVServiceReference.ProductDTOResp ProductConsultar(WebApplicationClient.AVServiceReference.ProductDTOReq req) {
            return base.Channel.ProductConsultar(req);
        }
        
        public System.Threading.Tasks.Task<WebApplicationClient.AVServiceReference.ProductDTOResp> ProductConsultarAsync(WebApplicationClient.AVServiceReference.ProductDTOReq req) {
            return base.Channel.ProductConsultarAsync(req);
        }
    }
}
