//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkSpace_AmericanVirtualWcfService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaProduct", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="ProductDTO")]
    [System.SerializableAttribute()]
    public class ListaProduct : System.Collections.Generic.List<DataTransferObject.ProductDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaUsers", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="UserDTO")]
    [System.SerializableAttribute()]
    public class ListaUsers : System.Collections.Generic.List<DataTransferObject.UserDTO> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaErrores", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObject", ItemName="Error")]
    [System.SerializableAttribute()]
    public class ListaErrores : System.Collections.Generic.List<DataTransferObject.Error> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserConsultar", ReplyAction="http://tempuri.org/IService1/UserConsultarResponse")]
        DataTransferObject.UserDTOResp UserConsultar(DataTransferObject.UserDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserConsultar", ReplyAction="http://tempuri.org/IService1/UserConsultarResponse")]
        System.Threading.Tasks.Task<DataTransferObject.UserDTOResp> UserConsultarAsync(DataTransferObject.UserDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductConsultar", ReplyAction="http://tempuri.org/IService1/ProductConsultarResponse")]
        DataTransferObject.ProductDTOResp ProductConsultar(DataTransferObject.ProductDTOReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductConsultar", ReplyAction="http://tempuri.org/IService1/ProductConsultarResponse")]
        System.Threading.Tasks.Task<DataTransferObject.ProductDTOResp> ProductConsultarAsync(DataTransferObject.ProductDTOReq req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WorkSpace_AmericanVirtualWcfService.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WorkSpace_AmericanVirtualWcfService.ServiceReference1.IService1>, WorkSpace_AmericanVirtualWcfService.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTransferObject.UserDTOResp UserConsultar(DataTransferObject.UserDTOReq req) {
            return base.Channel.UserConsultar(req);
        }
        
        public System.Threading.Tasks.Task<DataTransferObject.UserDTOResp> UserConsultarAsync(DataTransferObject.UserDTOReq req) {
            return base.Channel.UserConsultarAsync(req);
        }
        
        public DataTransferObject.ProductDTOResp ProductConsultar(DataTransferObject.ProductDTOReq req) {
            return base.Channel.ProductConsultar(req);
        }
        
        public System.Threading.Tasks.Task<DataTransferObject.ProductDTOResp> ProductConsultarAsync(DataTransferObject.ProductDTOReq req) {
            return base.Channel.ProductConsultarAsync(req);
        }
    }
}
